// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fintrack/Dashboard.tsx": () => import("../components/mockups/fintrack/Dashboard.tsx"),
  "./components/mockups/fintrack/LandingPage.tsx": () => import("../components/mockups/fintrack/LandingPage.tsx"),
  "./components/mockups/fintrack/LoginPage.tsx": () => import("../components/mockups/fintrack/LoginPage.tsx"),
  "./components/mockups/fintrack/Masters.tsx": () => import("../components/mockups/fintrack/Masters.tsx"),
  "./components/mockups/fintrack/MonthlyEntry.tsx": () => import("../components/mockups/fintrack/MonthlyEntry.tsx"),
  "./components/mockups/fintrack/Reports.tsx": () => import("../components/mockups/fintrack/Reports.tsx"),
  "./components/mockups/fintrack/SuggestionsPage.tsx": () => import("../components/mockups/fintrack/SuggestionsPage.tsx")
};
